name: jupyterenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip=20.2.4
  - nodejs=18.16.0
  - jupyterhub=4.0.2
  - jupyterlab
  - notebook
  - nb_conda
  - nb_conda_kernels
  - pip:
    - jupyterhub-nativeauthenticator
    - git+https://github.com/joebell/dockernel.git
# - git+https://github.com/joebell/jupyter-matlab-proxy.git
# - jupyter-matlab-proxy
    - matlabengine
    - matlab_kernel

######

