name: jupyterenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip=20.2.4
  - jupyterhub=4.0.2
  - jupyterlab=3.6.3
  - notebook=6.5.4
  - jupyterlab-git=0.42.0
  - pandoc=2.12
  - pip:
    - jupyterhub-nativeauthenticator==1.2.0
      #    - jupyterhub-idle-culler==1.2.1
    - git+https://github.com/joebell/dockernel.git
    - jupyterlab-spreadsheet-editor==0.6.1

