name: jupyterenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip=20.2.4
  - jupyterhub=4.0.2
  - jupyterlab
  - notebook
  - nb_conda
  - nb_conda_kernels
  - pip:
    - jupyterhub-nativeauthenticator
    - git+https://github.com/joebell/dockernel.git

############

