#!/bin/bash
#
# run.sh
#
# Starts the labnotebook system running.
#
#

########################################################

# Place paths to SSL cert and key here
# IF you don't have them, then leave th string blank: ""
ssl_cert="/etc/ssl/gait_mednet_ucla_edu.pem"
ssl_key="/etc/ssl/private/gait.mednet.ucla.edu.key"

#########################################################

# Check if an argument was provided
if [ $# -eq 0 ]; then
  echo "Usage: $0 <server_name>"
  exit 1
fi

# Store the first argument in the SERVER_NAME variable
SERVER_NAME="$1"


# Check if either ssl_cert or ssl_key is empty
if [ -z "$ssl_cert" ] || [ -z "$ssl_key" ]; then
    echo "Using self-signed SSL certificates."
    USE_SSL="false"
    ssl_cert_option=""
    ssl_key_option=""
else
    echo "Using externally signed SSL certificates."
    USE_SSL="true"
    ssl_cert_option="-v $ssl_cert:/etc/jupyterhub/ssl/my_cert.crt "
    ssl_key_option="-v $ssl_key:/etc/jupyterhub/ssl/my_key.key "
fi

# Check if NVIDIA kernel module is loaded
if lsmod | grep -q "nvidia"; then
    echo "NVIDIA kernel module is loaded."
    USE_GPU="true"
    gpu_option="--gpus all"
else
    echo "NVIDIA kernel module is not loaded."
    USE_GPU="false"
    gpu_option=""
fi

# Get the Docker group ID in the host to match it in the container
DOCKER_GROUP_ID=$(getent group docker | cut -d: -f3)
DOCKER_RUN_COMMAND="docker run -d \
    --init \
    --restart unless-stopped \
    --name $SERVER_NAME \
    -e "USE_GPU=$USE_GPU" \
    $gpu_option \
    --network=host \
    -v $SERVER_NAME-homedirs:/home \
    -v $SERVER_NAME-etc:/etc \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e "USE_SSL=$USE_SSL" \
    -e "DOCKER_GROUP_ID=$DOCKER_GROUP_ID" \
    $ssl_cert_option \
    $ssl_key_option \
    $SERVER_NAME:latest"


# Check if a container named "labnotebook" exists
if docker ps -a -q -f "name=$SERVER_NAME" | grep -q .; then
    echo "A container named $SERVER_NAME already exists."
    read -p "Do you want to restart it? (y/n): " choice
    if [ "$choice" == "y" ]; then
        docker start $SERVER_NAME
        echo "Container $SERVER_NAME has been restarted."
    else
        # Remove the existing container
        docker rm $SERVER_NAME
        echo "Container $SERVER_NAME has been removed."

        # Start a new container
        eval $DOCKER_RUN_COMMAND
    fi
else
    # Container does not exist, so start a new one
    eval $DOCKER_RUN_COMMAND
fi

